-- Mindfries — seed the Targets panel with the hand-picked company list.
--
-- 102 companies. Run AFTER the three migrations (target_companies
-- must exist). Safe to re-run: 'on conflict (company_key) do nothing' leaves a
-- company already in the table exactly as it is, edits and all.
--
-- company_key is computed here with the app's own companyKey() rule
-- (lower-cased, punctuation to spaces, legal suffixes dropped) so the unique
-- constraint and the app's duplicate check agree. Don't hand-write it.
--
-- owner is left null: nobody has been assigned these yet, and the panel shows
-- "unassigned" honestly rather than guessing. next_action_due is null too, so
-- nothing shows as overdue on day one.

insert into target_companies
  (name, company_key, website, priority, stage, why_target, notes, source, next_action)
values
  ('Peoplebox.ai', 'peoplebox ai', 'https://www.peoplebox.ai/', 'A', 'researching', 'AI-native talent platform; strong strategic fit and active hiring signal', '35 employees; Bengaluru; YC S22; recruiting/HR-tech company; especially useful as a design-partner or integration conversation.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Weekday', 'weekday', 'https://www.weekday.works/', 'A', 'researching', 'Recruiting company where Mindfries can complement sourcing with evidence of real ability', '38 employees; Bengaluru; YC W21; active hiring signal; potential partner: Weekday finds talent, Mindfries validates talent.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Landeed', 'landeed', 'https://www.landeed.com/', 'A', 'researching', 'Small AI-native proptech team where each technical hire has high leverage', '35 employees; Hyderabad; YC S22; active hiring signal; AI/property intelligence.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('AlgoTest', 'algotest', 'https://algotest.in/', 'A', 'researching', 'Technical fintech with engineering-heavy hiring and real-world work that can become assessments', '40 employees; Delhi; YC S22; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Rivia.AI', 'rivia ai', 'https://www.rivia.ai/', 'A', 'researching', 'Very small AI/SaaS team; ideal environment for experimental hiring assessment', 'Small AI-native team; Bengaluru; YC W26; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('BusinessOnBot', 'businessonbot', 'https://businessonbot.com/', 'A', 'researching', 'Small SaaS/AI company where founder-led hiring makes a new assessment workflow easy to test', '25 employees; Bengaluru; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Kodo', 'kodo', 'https://www.kodo.in/', 'A', 'researching', 'Fintech startup with technical/product hiring needs and a relatively compact team', '45 employees; Mumbai; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Betterhalf', 'betterhalf', 'https://betterhalf.ai/', 'B', 'researching', 'Consumer tech company where product and engineering hires affect a broad product surface', '25 employees; Bengaluru; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Material Depot', 'material depot', 'https://materialdepot.in/', 'B', 'researching', 'Marketplace/proptech company with product, engineering and operations work that maps well to work-sample assessment', '50 employees; Bengaluru; YC W22; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('IMT Care', 'imt care', 'https://www.imt.care/', 'A', 'researching', 'B2B health/insurance SaaS with AI angle; strong fit for role-specific work assessments', '23 employees; Mumbai; YC W22; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Neodocs', 'neodocs', 'https://neodocs.in/', 'B', 'researching', 'AI-enabled healthtech with technical and product work where real-world assessment is valuable', '20 employees; Mumbai; YC S21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Coulomb AI', 'coulomb ai', 'https://coulomb.ai/', 'A', 'researching', 'Tiny AI/climate-tech team where every technical hire matters', '10 employees; Bengaluru; YC S21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Retape', 'retape', 'https://retape.ai/', 'A', 'researching', 'AI operating-system startup; ideal early design partner for adaptive work assessment', '3 employees; Bengaluru; YC W23; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Raven', 'raven', 'https://www.raven.ai/', 'A', 'researching', 'AI assistants for manufacturing; domain-heavy technical work is hard to test with generic interviews', '4 employees; Bengaluru; YC S22; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Optifye.ai', 'optifye ai', 'https://optifye.ai/', 'A', 'researching', 'Computer-vision/AI startup where practical problem solving matters more than trivia', '8 employees; New Delhi; YC W25; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cardboard', 'cardboard', 'https://www.cardboard.video/', 'A', 'researching', 'Agentic video-editing startup with product and engineering work that can be simulated', '8 employees; Bengaluru; YC W26; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('SalaryBox', 'salarybox', 'https://salarybox.in/', 'B', 'researching', 'B2B SaaS/payroll company with recurring technical and operations hiring', '40 employees; Gurugram; YC S21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Codingal', 'codingal', 'https://www.codingal.com/', 'B', 'researching', 'AI/coding education company with engineering, product and education roles', '100 employees; Bengaluru; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('RocketSDR', 'rocketsdr', 'https://rocketsdr.com/', 'A', 'researching', 'AI sales-outreach company; strong fit for assessing sales and GTM execution as well as engineering', '30 employees; Bengaluru; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('GroMo', 'gromo', 'https://gromo.in/', 'B', 'researching', 'Fintech distribution platform with recurring hiring across product, engineering and GTM', '100 employees; Gurugram; YC W21; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cone', 'cone', 'https://www.cone.io/', 'A', 'researching', 'AI-powered work operating system for accounting workflows; strong B2B/AI hiring fit', 'YC-backed Indian SaaS/AI startup; current YC directory signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('SuperKalam', 'superkalam', 'https://www.superkalam.com/', 'B', 'researching', 'AI-enhanced learning product where product/engineering candidates can be evaluated against real product problems', 'YC-backed Indian edtech/AI startup; current YC hiring ecosystem signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Clinikally', 'clinikally', 'https://www.clinikally.com/', 'B', 'researching', 'Growing digital health platform with technical, product, marketing and operations hiring', '125 employees; Gurugram; YC S22; active hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Helloverify', 'helloverify', 'https://helloverify.com/', 'B', 'researching', 'Hiring/background-verification platform is itself close to the hiring workflow and can value better assessment evidence', '600 employees; Noida; active hiring signal; larger but strategically relevant.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cityfurnish', 'cityfurnish', 'https://www.cityfurnish.com/', 'C', 'researching', 'Consumer marketplace with recurring operations and product hiring', 'India; current YC jobs ecosystem shows active roles; useful secondary target.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Nash', 'nash', 'https://www.nash.ai/', 'A', 'researching', 'Digital logistics infrastructure; forward-deployed and engineering work is highly role-specific', 'YC S21; current YC hiring signal including engineering/solutions roles.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('AssemblyAI', 'assemblyai', 'https://www.assemblyai.com/', 'A', 'researching', 'AI model/API company with difficult engineering and ML hiring', '51-200 employees; actively hiring; strong AI/engineering fit.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Recall.ai', 'recall ai', 'https://www.recall.ai/', 'A', 'researching', 'API/AI infrastructure startup; small technical team makes practical assessment valuable', 'YC-backed AI/API startup; current hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Agave', 'agave', 'https://www.agaveapi.com/', 'A', 'researching', 'Construction/fintech API company with technical domain knowledge; strong work-sample fit', 'YC-backed startup; current hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Taktile', 'taktile', 'https://taktile.com/', 'A', 'researching', 'AI decisioning platform with high-skill engineering/product roles', 'YC-backed B2B AI company; current hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Lamar Health', 'lamar health', 'https://www.lamarhealth.com/', 'A', 'researching', 'Healthcare workflow startup where practical product and engineering judgment matters', 'YC W21; current YC hiring signal including Product Engineer.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Finni Health', 'finni health', 'https://www.finnihealth.com/', 'A', 'researching', 'Healthcare operations startup with technical and operational roles', 'YC W23; current YC hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Great Question', 'great question', 'https://greatquestion.co/', 'A', 'researching', 'User-research platform; product, engineering and customer-facing work can be assessed through realistic tasks', 'US SaaS startup; good mid-size design-partner profile.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Provision', 'provision', 'https://www.provision.ai/', 'A', 'researching', 'Construction SaaS with domain-specific product/engineering work', 'YC-backed startup; current hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Tank Payments', 'tank payments', 'https://tankpayments.com/', 'A', 'researching', 'Fintech infrastructure for trucking; technical/domain judgment is central', 'YC S22; current YC hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Wasmer', 'wasmer', 'https://wasmer.io/', 'A', 'researching', 'Developer infrastructure company; highly technical hiring makes real-work assessment compelling', 'YC-backed infrastructure startup; current hiring ecosystem signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Medplum', 'medplum', 'https://www.medplum.com/', 'A', 'researching', 'Developer-first healthcare infrastructure; strong engineering and product assessment use case', 'YC S22; current YC hiring signal including software engineers.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Infer', 'infer', 'https://www.infer.ai/', 'A', 'researching', 'AI operating system for insurance agencies; domain-specific applied AI work is ideal for Mindfries', 'YC S21; current YC hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Mason', 'mason', 'https://www.bymason.com/', 'B', 'researching', 'Hardware/software infrastructure startup with full-stack roles', 'YC-backed company; current YC hiring signal.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Retool', 'retool', 'https://retool.com/', 'B', 'researching', 'Developer platform with sophisticated engineering hiring and real product work', 'Larger scale; excellent credibility target for technical assessment.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('PostHog', 'posthog', 'https://posthog.com/', 'A', 'researching', 'Product analytics company with engineering/product-heavy hiring and strong startup culture', 'Developer-focused SaaS; strong experimentation culture; ideal reference customer profile.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Vanta', 'vanta', 'https://www.vanta.com/', 'B', 'researching', 'Security/compliance SaaS with recurring technical and customer-facing hiring', 'Growing SaaS company; strong B2B hiring use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Clay', 'clay', 'https://www.clay.com/', 'A', 'researching', 'AI-native GTM platform; excellent fit for assessing product, engineering and growth roles', 'Fast-growing AI/SaaS profile; strong candidate-work alignment.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Attio', 'attio', 'https://attio.com/', 'A', 'researching', 'Modern CRM with strong product/design/engineering culture', 'Small-to-mid-sized product company; ideal for product-centric work assessments.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Linear', 'linear', 'https://linear.app/', 'B', 'researching', 'Highly selective product/engineering organization; strong benchmark customer if reachable', 'Selective technical hiring; strategic credibility target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Modal', 'modal', 'https://modal.com/', 'A', 'researching', 'Cloud platform for AI workloads; hard technical hiring is a strong Mindfries use case', 'AI infrastructure; engineering-heavy team.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Together AI', 'together ai', 'https://www.together.ai/', 'B', 'researching', 'AI infrastructure company with ML/software hiring needs', 'AI-native engineering organization; strong technical assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Pinecone', 'pinecone', 'https://www.pinecone.io/', 'B', 'researching', 'Vector database company with specialized engineering hiring', 'Developer infrastructure; practical technical work is valuable to assess.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Replicate', 'replicate', 'https://replicate.com/', 'A', 'researching', 'AI model platform with deep engineering/product work', 'AI infrastructure; strong work-sample and adaptive interview fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Baseten', 'baseten', 'https://www.baseten.co/', 'A', 'researching', 'AI inference platform; small expert teams make high-quality technical hiring critical', 'AI infrastructure; strong technical hiring fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Fireworks AI', 'fireworks ai', 'https://fireworks.ai/', 'A', 'researching', 'Generative AI infrastructure company with specialized ML/engineering hiring', 'AI infrastructure; strong technical assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Decagon', 'decagon', 'https://decagon.ai/', 'A', 'researching', 'AI customer-support agents; roles require real product/AI reasoning', 'AI-native startup; excellent adaptive-assessment use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Sierra', 'sierra', 'https://sierra.ai/', 'A', 'researching', 'AI agents for enterprises; product and engineering candidates can be tested against realistic agent problems', 'AI-native company; strong strategic target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Harvey', 'harvey', 'https://www.harvey.ai/', 'B', 'researching', 'Legal AI where domain-specific reasoning and practical output matter', 'Fast-growing AI company; strong high-skill hiring use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Abridge', 'abridge', 'https://www.abridge.com/', 'B', 'researching', 'Healthcare AI with engineering/ML/product hiring and high stakes', 'AI healthcare; practical work assessment can differentiate candidates.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('EvenUp', 'evenup', 'https://www.evenuplaw.com/', 'B', 'researching', 'Legal AI/automation company with cross-functional hiring', 'AI/legaltech; strong use case for work-sample assessments.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Mercury', 'mercury', 'https://mercury.com/', 'B', 'researching', 'Fintech with sophisticated product and engineering organization', 'Large but startup-oriented; strategic credibility account.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Ramp', 'ramp', 'https://ramp.com/', 'B', 'researching', 'Fintech with substantial recurring hiring and complex real-world work', 'Large growth-stage company; high potential but longer sales cycle.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Glean', 'glean', 'https://www.glean.com/', 'B', 'researching', 'Enterprise AI/search with broad engineering and product hiring', 'AI-native growth company; strong strategic target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('incident.io', 'incident io', 'https://incident.io/', 'A', 'researching', 'Developer infrastructure company where engineering and product work can be evaluated realistically', 'UK SaaS; compact, engineering-heavy profile.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Raycast', 'raycast', 'https://www.raycast.com/', 'A', 'researching', 'Developer productivity company with highly selective product/engineering hiring', 'UK/remote product company; strong technical assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('PolyAI', 'polyai', 'https://www.poly.ai/', 'B', 'researching', 'Conversational AI company with ML, engineering and enterprise roles', 'UK AI company; strong technical hiring fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Humaans', 'humaans', 'https://humaans.io/', 'A', 'researching', 'HR tech company; direct strategic relevance to hiring workflow and people systems', 'UK SaaS; strong partnership/design-partner potential.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cleo', 'cleo', 'https://web.meetcleo.com/', 'B', 'researching', 'Consumer fintech with product/engineering hiring', 'UK fintech; recurring technical/product hiring.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Pleo', 'pleo', 'https://www.pleo.io/', 'B', 'researching', 'Fintech spend-management platform with recurring cross-functional hiring', 'European scale-up; good mid-market target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Yonder', 'yonder', 'https://www.yondercard.com/', 'A', 'researching', 'Fintech/card startup where practical product and risk work matters', 'UK fintech; good fit for role-specific assessment.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Personio', 'personio', 'https://www.personio.com/', 'B', 'researching', 'HR software scale-up with substantial product/engineering hiring', 'European scale-up; strong strategic HR-tech account.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Forto', 'forto', 'https://forto.com/', 'B', 'researching', 'Digital freight-forwarding company with technical/product/operations hiring', 'European logistics tech; work-sample assessment maps well to operations + tech roles.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Staffbase', 'staffbase', 'https://www.staffbase.com/', 'B', 'researching', 'B2B employee-communications SaaS with recurring hiring', 'European SaaS scale-up; good mid-market target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Pitch', 'pitch', 'https://pitch.com/', 'A', 'researching', 'Product-led collaboration software; strong product/design/engineering culture', 'Berlin-based SaaS; excellent product-work assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Parloa', 'parloa', 'https://www.parloa.com/', 'A', 'researching', 'AI voice agents; specialized engineering/product hiring', 'Berlin AI company; strong current market fit for adaptive technical assessment.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cognigy', 'cognigy', 'https://www.cognigy.com/', 'B', 'researching', 'Enterprise conversational AI platform with technical hiring needs', 'German AI/SaaS; strong technical and enterprise role fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('DeepL', 'deepl', 'https://www.deepl.com/', 'B', 'researching', 'AI language company with highly specialized technical hiring', 'Large strategic account; credibility potential.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Helsing', 'helsing', 'https://helsing.ai/', 'B', 'researching', 'AI/defense technology with highly specialized technical hiring', 'European deep-tech; extremely high value per technical hire.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Mistral AI', 'mistral ai', 'https://mistral.ai/', 'B', 'researching', 'Frontier AI company where technical hiring quality is critical', 'France; larger strategic account; high-signal AI brand.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Qonto', 'qonto', 'https://qonto.com/', 'B', 'researching', 'Fintech scale-up with recurring engineering/product hiring', 'European fintech; strong mid-market/scale-up target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Pennylane', 'pennylane', 'https://www.pennylane.com/', 'A', 'researching', 'Accounting SaaS with complex real-world workflows suitable for work-sample assessment', 'France SaaS; strong B2B/product fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Pigment', 'pigment', 'https://www.pigment.com/', 'A', 'researching', 'Planning SaaS with product/engineering/customer roles', 'France SaaS; mid-market target with strong work context.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Back Market', 'back market', 'https://www.backmarket.com/', 'B', 'researching', 'Marketplace with broad product, engineering and operations hiring', 'Large but startup-style culture; strategic target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Sorare', 'sorare', 'https://sorare.com/', 'B', 'researching', 'Gaming/sports-tech company with product, engineering and data hiring', 'European product company; strong practical assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Kry', 'kry', 'https://www.kry.se/', 'B', 'researching', 'Digital health platform with product/engineering/clinical operations', 'Nordic scale-up; strong cross-functional hiring use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Einride', 'einride', 'https://www.einride.tech/', 'A', 'researching', 'Autonomous/electric freight company with deep technical and operational roles', 'Swedish deep-tech; practical assessment highly relevant.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Lovable', 'lovable', 'https://lovable.dev/', 'A', 'researching', 'AI-native software creation company; fast-moving technical/product hiring', 'Nordic AI-native startup; strong strategic target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cohere', 'cohere', 'https://cohere.com/', 'B', 'researching', 'Enterprise AI with specialized research/engineering hiring', 'Canada AI leader; strategic credibility target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Ada', 'ada', 'https://www.ada.cx/', 'A', 'researching', 'AI customer-service platform; practical agent/product work maps directly to assessment', 'Toronto AI/SaaS; strong product and engineering fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Clio', 'clio', 'https://www.clio.com/', 'B', 'researching', 'Legal SaaS with substantial product/engineering hiring', 'Canadian scale-up; strong recurring hiring use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('BenchSci', 'benchsci', 'https://www.benchsci.com/', 'A', 'researching', 'AI-powered life-science platform with specialized product/engineering hiring', 'Toronto AI/healthtech; high-skill hiring fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Waabi', 'waabi', 'https://waabi.ai/', 'A', 'researching', 'Autonomous trucking AI; highly specialized engineering hiring', 'Toronto deep-tech; practical technical assessment is highly relevant.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('StackAdapt', 'stackadapt', 'https://www.stackadapt.com/', 'B', 'researching', 'Adtech platform with substantial technical and commercial hiring', 'Canadian scale-up; recurring hiring.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Wiz', 'wiz', 'https://www.wiz.io/', 'B', 'researching', 'Cloud security company with high-volume specialized technical hiring', 'Large strategic account; cybersecurity hiring is a strong fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Cyera', 'cyera', 'https://www.cyera.com/', 'A', 'researching', 'Data security startup with technical and enterprise GTM hiring', 'Israeli cybersecurity scale-up; strong practical assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Gong', 'gong', 'https://www.gong.io/', 'B', 'researching', 'Revenue intelligence platform with engineering, product and GTM hiring', 'Large strategic account; strong multi-persona assessment opportunity.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Firebolt', 'firebolt', 'https://www.firebolt.io/', 'A', 'researching', 'Cloud data warehouse with highly technical hiring', 'Israeli data infrastructure company; engineering assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Island', 'island', 'https://www.island.io/', 'B', 'researching', 'Enterprise browser/cybersecurity company with specialized hiring', 'Israeli-founded cybersecurity scale-up; strong technical fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Culture Amp', 'culture amp', 'https://www.cultureamp.com/', 'B', 'researching', 'People analytics SaaS; direct adjacency to talent workflows', 'Australian scale-up; strong HR-tech strategic fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('SafetyCulture', 'safetyculture', 'https://safetyculture.com/', 'B', 'researching', 'Operations SaaS with recurring product/engineering hiring', 'Australian scale-up; broad work-sample opportunities.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Immutable', 'immutable', 'https://www.immutable.com/', 'A', 'researching', 'Web3/gaming platform with technical/product hiring', 'Australian technology company; strong technical assessment use case.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Airwallex', 'airwallex', 'https://www.airwallex.com/', 'B', 'researching', 'Global fintech with substantial engineering/product hiring', 'Australia/Singapore footprint; strategic scale-up target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Nium', 'nium', 'https://www.nium.com/', 'A', 'researching', 'Global payments infrastructure with fintech/engineering hiring', 'Singapore fintech; strong domain-specific work assessment fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Aspire', 'aspire', 'https://aspireapp.com/', 'A', 'researching', 'B2B fintech with product, engineering and GTM hiring', 'Singapore fintech; good mid-market target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('PatSnap', 'patsnap', 'https://www.patsnap.com/', 'B', 'researching', 'AI/data platform for R&D teams with technical hiring', 'Singapore/global SaaS; strategic AI/product target.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch'),
  ('Carro', 'carro', 'https://carro.sg/', 'B', 'researching', 'Automotive marketplace with technology and operations hiring', 'Singapore scale-up; practical cross-functional hiring fit.', 'other', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch')
on conflict (company_key) do nothing;

-- How many landed:
select count(*) as targets from target_companies;

-- ── Held back ───────────────────────────────────────────────────────────────
-- "AssemblyAI Canada" is the same company as "AssemblyAI" (both assemblyai.com). The unique
-- constraint wouldn't catch it, because the keys differ, but the panel's own
-- Add form matches on website host and would refuse it as a duplicate.
--
-- Uncomment only if it really is a separate entity worth tracking on its own:
--
-- insert into target_companies
--   (name, company_key, website, priority, stage, why_target, notes, source, next_action)
-- values
-- ('AssemblyAI Canada', 'assemblyai canada', 'https://www.assemblyai.com/', 'A', 'researching', 'AI model/API company with engineering and ML hiring', '51-200 employee profile; actively hiring; Canada-linked presence.', 'tracker', 'Find founder/CTO/Head of Talent; identify one active role and send a role-specific Mindfries pitch')
-- on conflict (company_key) do nothing;
